"""empty message

Revision ID: ce5719e042b8
Revises: e0b4a50e06ac
Create Date: 2025-06-27 21:08:22.908378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5719e042b8'
down_revision = 'e0b4a50e06ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('imageUrl', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_column('imageUrl')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
